export const CardActionTypes = {
    GET_DATA: 'GET_DATA',
    TOGGLE_LIKE: 'TOGGLE_LIKE',
    TOGGLE_DISLIKE: 'TOGGLE_DISLIKE',
    TOGGLE_SHARE: 'TOGGLE_SHARE',
    ADD_COMMENT: 'ADD_COMMENT',
    UPDATE_STATUS: 'UPDATE_STATUS'
};